services:
  vite:
    build: .
    container_name: vite-server
    command: yarn dev
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine